# Requires 10.10 for the definition of AT_FDCWD
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - 10.12                  # [osx and x86_64]
# Requires 10.12 for clock_gettime
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 10.12                  # [osx and x86_64]
