{% set name = "htop" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/htop-dev/htop/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c0661f0ae5f4e2874da250b60cd515e4ac4c041583221adfe95f10e18d1a4e6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - automake
    - libtool
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - ncurses

  run:
    - ncurses

test:
  commands:
    - htop --version

about:
  home: https://htop.dev/
  license: GPL-2.0-only
  license_file: COPYING
  summary: htop is an interactive text-mode process viewer for Unix systems. It aims to be a better 'top'
  dev_url: https://github.com/htop-dev/htop/

extra:
  recipe-maintainers:
    - chrisburr
    - keuv-grvl
